version: '3'

services:
  zipper:
    image: wushaobo/zipper:latest
    command: /opt/zipper/run.sh
    ports:
      - "24080:80"
    env_file:
      - config.env
    volumes:
      - "../../logs:/var/log/zipper"

  redis:
    image: redis:3.2.12-alpine
