sudo: required

language: python

services:
  - docker

before_script:
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"

script:
  - ./build.sh build-image
  - ./build.sh push-to-registry

notifications:
  email: false
